// <auto-generated />
// Rendered from the payload lock by the repository build tooling. Do not edit.

#nullable enable

namespace Jellyfin.Plugin.AutoSubSync.Cli;

public enum PayloadArchiveFormat
{
    Zip,
    TarGz
}

// The tool builds this assembly is pinned to, and the hashes that prove them.
public static class PayloadManifest
{
    public static readonly PayloadTool AssyCli = new(
        "assy-cli",
        "assy-cli",
        "2.0",
        // ! Compiled in. A configurable download host is arbitrary code execution.
        "https://github.com/AdamHarrison99/jellyfin-plugin-autosubsync/releases/download/payload-v2.0",
        [
            new("win-x64", "assy-cli-2.0-win-x64.zip", "c29e41e32a8ef36c979b5ee71779f195f4697e880d91490baf4242d42ca190e2", 42254865L, PayloadArchiveFormat.Zip),
            new("linux-x64", "assy-cli-2.0-linux-x64.zip", "936f3ba5d2b20eb7407e4d6db5753d16962ab33daeb3d31349b9ed6b0ca85bfb", 94421554L, PayloadArchiveFormat.Zip)
        ]);

    public static readonly PayloadTool Seconv = new(
        "seconv",
        "seconv",
        "5.1.0",
        // ! Compiled in. A configurable download host is arbitrary code execution.
        "https://github.com/SubtitleEdit/subtitleedit/releases/download/v5.1.0",
        [
            new("win-x64", "SeConv-Windows-x64.zip", "ce081a6c6844d44cb1373ee501a963c9e37c788bf757c2fa0b39821ef9969839", 42300410L, PayloadArchiveFormat.Zip),
            new("linux-x64", "SeConv-Linux-x64.tar.gz", "3354dfeb4452b0dd8a11d8f3066c31a3116e2cbc137f271ac6b7e4f91896ba11", 41021313L, PayloadArchiveFormat.TarGz),
            new("linux-arm64", "SeConv-Linux-ARM64.tar.gz", "ab58891abd54a1604fdf5956c340159bd2efbcaef8cf2c69d97fcc55b83b4718", 38962486L, PayloadArchiveFormat.TarGz),
            new("osx-arm64", "SeConv-macOS-ARM64.zip", "d734ac8ca2d30ad2a09838bf0c1801ed83b0349385f782262102e5852d1dca21", 41767806L, PayloadArchiveFormat.Zip)
        ]);

    public static readonly IReadOnlyList<PayloadTool> All = [AssyCli, Seconv];
}

public record PayloadAsset(
    string Rid, string FileName, string Sha256, long Size, PayloadArchiveFormat Format);

public record PayloadTool(
    string Name,
    string BinaryName,
    string Version,
    string BaseUrl,
    IReadOnlyList<PayloadAsset> Assets)
{
    public string ExecutableName
        => OperatingSystem.IsWindows() ? BinaryName + ".exe" : BinaryName;

    public PayloadAsset? For(string? rid)
        => Assets.FirstOrDefault(a => string.Equals(a.Rid, rid, StringComparison.Ordinal));

    public string UrlFor(PayloadAsset asset) => $"{BaseUrl}/{asset.FileName}";
}
